on:
  push:
    tags:
      - 'v*.*.*'

name: Build Electron Application

jobs:
  build:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1
      
      - name: Install dependencies
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
          pak::pkg_install(".")
          pak::pkg_install("chasemc/electricShine")
          ActiveForms::build_app("AF_build")
        shell: Rscript {0}
      
      - name: Get Package Version
        id: pkg_ver
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      
      - name: Package build
        env:
          PACKAGE_VER: ${{ steps.pkg_ver.outputs.tag }}
        run: |
          zip -r -X ActiveForms_$PACKAGE_VER.zip AF_build
      
      - name: Upload release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ActiveForms_${{ steps.pkg_ver.outputs.tag }}.zip
