on:
  push:
    tags:
      - 'v*.*.*'

name: Build Electron Application

jobs:
  build:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1
      
      - name: Install dependencies
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
          pak::pkg_install(".")
          pak::pkg_install("roblen001/electricShine")
        shell: Rscript {0}

      - name: Build Application
        run: ActiveForms::build_app("AF_build")
        shell: Rscript {0}
      
      - name: Compress Installer
        env:
          PACKAGE_VER: ${{ steps.pkg_ver.outputs.tag }}
        run: |
          $AF_PATH=$(ls AF_build/ActiveForms/dist/ | Select-String -Pattern "\.exe$")
          zip -r -X ActiveForms-win.zip $AF_PATH
      
      - name: Upload release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ActiveForms-win.zip
